[build]
  command = "npm run build"
  publish = "build/"

# https://docs.netlify.com/routing/headers/#syntax-for-the-headers-file
[[headers]]
  for = "/images/personnes/*"

  [headers.values]
    cache-control = '''
      public,
      max-age=3600,
      must-revalidate'''
